<<<<<<< HEAD
php:
  preset: laravel
  disabled:
    - unused_use
js: true
css: true
=======
php:
  preset: laravel
  disabled:
    - unused_use
js: true
css: true
>>>>>>> 96b967099916ef531958609f80f4e4e1769e14e3
